version: 2

defaults: &defaults
  working_directory: ~/project/nice-mail
  docker:
    - image: circleci/node:8.9.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-nice-mail-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-nice-mail-{{ .Branch }}-
            - v1-nice-mail-
      - run: npm install
      - save_cache:
          key: v1-nice-mail-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - nice-mail

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
